//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hostel_Management_SystemEntities : DbContext
    {
        public Hostel_Management_SystemEntities()
            : base("name=Hostel_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<BookingRequest> BookingRequests { get; set; }
        public virtual DbSet<Hostel_Rooms> Hostel_Rooms { get; set; }
        public virtual DbSet<Hostel_Images> Hostel_Images { get; set; }
        public virtual DbSet<Hostel> Hostels { get; set; }
        public virtual DbSet<FavoriteHostel> FavoriteHostels { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Feedback_Facilites> Feedback_Facilites { get; set; }
    }
}
