//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hostel_Rooms
    {
        public int Id { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> TotalRooms { get; set; }
        public Nullable<int> BedsInRoom { get; set; }
        public string Facilites { get; set; }
        public string Description { get; set; }
        public Nullable<int> H_Id { get; set; }
    }
}
