//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRequest
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> H_Id { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> NoOfBeds { get; set; }
        public string Status { get; set; }
        public Nullable<int> R_Id { get; set; }
    }
}
